CREATE DATABASE IF NOT EXISTS sge CHARACTER SET utf8 COLLATE utf8_general_ci;

USE sge;

CREATE TABLE IF NOT EXISTS admin (
	username VARCHAR(25) NOT NULL,
	email VARCHAR(100) NOT NULL,
	gender VARCHAR(1) NOT NULL,
	role VARCHAR(25) NOT NULL,
	password VARCHAR(25) NOT NULL,
	PRIMARY KEY (email)
); 


CREATE TABLE IF NOT EXISTS coadmin {
	username VARCHAR(25) NOT NULL,
	email VARCHAR(100) NOT NULL,
	gender VARCHAR(1) NOT NULL,
	role VARCHAR(25) NOT NULL,
	password VARCHAR(25) NOT NULL,
	PRIMARY KEY (email)
}